version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    image: devops-backend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfilebackend
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - Url_Db=mongodb://admin:password123@mongodb:27017/
    depends_on:
      - mongodb
    restart: always

  frontend:
    image: devops-frontend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfilefrontend
    container_name: frontend
    env_file:
      - .env.docker
    ports:
      - "5371:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
