version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db

  backend:
    # On donne un nom explicite à l'image avec la version
    image: devops-backend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfilebackend
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      # Note: Idéalement, mettez cette URL dans les credentials Jenkins, pas en clair ici
      - Url_Db=mongodb+srv://baccarhanine:pvKCqF5yZEsIQEZj@cluster0.oisbgie.mongodb.net/
    depends_on:
      - mongodb

  frontend:
    # Idem pour le frontend
    image: devops-frontend:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfilefrontend
    env_file:
      - .env.docker
    container_name: frontend
    ports:
      - "5371:80"  
    depends_on:
      - backend

volumes:
  mongo-data: